version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: altia_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8090:80"
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: altia_bd
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: altia_db
      MYSQL_USER: altia_user
      MYSQL_PASSWORD: altia_pswd
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
